---

- name: ensure tasks run only on selected os releases
  block:

    - name: enable rpfusion repositories
      ansible.builtin.include_role:
        name: repo__rpm_fusion

    - name: install steam
      ansible.builtin.package:
        name: "{{ steam.packages }}"
        state: latest

  when: ansible_distribution == "Fedora"

...
